// Build-time module: extracts brand icons from an iconify collection
// (configurable via `externalLinkIcons.collection`), bundles them
// with a fallback "external link" glyph, and emits a CSS file that
// decorates external links inside `.prose` with a host-aware
// `::after` icon — branded marks for each entry in
// `externalLinkIcons.brands`, and a generic open-in-new glyph for
// everything else.
//
// The generated file is appended to `nuxt.options.css` so it ships in
// the regular client bundle alongside `app/assets/css/main.css`.

import type { IconifyJSON } from '@iconify/types';
import { addTemplate, defineNuxtModule, useLogger } from 'nuxt/kit';

// Module name — used for the Nuxt module identity, the generated
// CSS filename (under `.nuxt/`), and the consola logger tag.
const TEMPLATE_NAME = 'external-link-icons';
const TEMPLATE_FILENAME = `${TEMPLATE_NAME}.css`;

// Tagged consola instance for build-time diagnostics. Tags appear
// as a styled prefix in formatted output, so log messages don't
// repeat the module name.
const logger = useLogger(TEMPLATE_NAME);

/**
 * One configured brand icon: an iconify icon name plus one or
 * more bare hostnames whose `https://host/...` URLs should be
 * decorated with that brand's glyph.
 */
export interface BrandIcon {
  /** Iconify icon name within the configured collection. */
  name: string

  /** Bare hostname, or list of hostnames, for the brand. */
  host: readonly string[] | string
}

/** Configuration for the external-link-icons module. */
export interface ModuleOptions {
  /** Iconify collection name to load brand glyphs from. */
  collection: string

  /** Brand icon entries; each ships a CSS cascade rule for its hosts. */
  brands: readonly BrandIcon[]

  /** SVG markup for the fallback "external link" glyph. */
  externalLinkSvg: string

  /** CSS indentation prefix for the generated file. */
  indent: string
}

// Default brand icons. Each host is wrapped in `https://…/` so
// selectors anchor at the URL start and stop at the host boundary
// — `http://` is intentionally omitted because every modern brand
// host serves over HTTPS. Order is preserved in the output.
const DEFAULT_BRANDS: readonly BrandIcon[] = [
  { name: 'npm', host: 'www.npmjs.com' },
  { name: 'go', host: 'pkg.go.dev' },
  { name: 'github', host: ['github.com', 'gist.github.com'] },
];

// Bare-hostname pattern: ASCII letters, digits, dots, and hyphens,
// anchored, with leading/trailing alphanumerics. Rejects empty
// strings, schemes, ports, paths, and stray punctuation. The `i`
// flag mirrors the case-insensitive flag on the downstream CSS
// attribute selector.
const HOST_PATTERN = /^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/i;

// Default lucide-style "external link" glyph for non-brand external
// links. Stored as a complete SVG element so it shares the brand-icon
// data-URI pipeline without needing an extra iconify pack on disk.
const DEFAULT_EXTERNAL_LINK_SVG = [
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"',
  ' fill="none" stroke="currentColor" stroke-width="2"',
  ' stroke-linecap="round" stroke-linejoin="round">',
  '<path d="M14 3h7v7"/>',
  '<path d="M21 3l-9 9"/>',
  '<path d="M19 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h6"/>',
  '</svg>',
].join('');

const HEADER_COMMENT =
  '/* Generated by modules/external-link-icons.ts — do not edit. */';

// Default indentation for emitted CSS blocks. Threaded through every
// wrapper helper as the `indent` parameter default so each function
// remains callable standalone with no setup.
const DEFAULT_INDENT = '  ';

// Default options merged with the user's `externalLinkIcons` config
// in `nuxt.config.ts`. Users supply a `Partial<ModuleOptions>` and
// the missing fields fall through to these defaults.
//
// If this module is ever published as a standalone package, export
// `DEFAULT_BRANDS`, `DEFAULT_EXTERNAL_LINK_SVG`, and `DEFAULT_OPTIONS`
// so consumers can spread them when extending — e.g.
// `brands: [...DEFAULT_BRANDS, myBrand]`. Embedded use inside this
// repo doesn't need the export because the source is editable in
// place.
const DEFAULT_OPTIONS: ModuleOptions = {
  collection: 'simple-icons',
  brands: DEFAULT_BRANDS,
  externalLinkSvg: DEFAULT_EXTERNAL_LINK_SVG,
  indent: DEFAULT_INDENT,
};

/** Wrap an iconify body in a complete `<svg>` element. */
function wrapBrandSVG(
  body: string,
  width: number,
  height?: number,
): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height ?? width}">`,
    body,
    '</svg>',
  ].join('');
}

/** Encode an SVG string as a base64 data URI. */
function svgDataURI(svg: string): string {
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
}

/** Load an iconify collection JSON at build time, or warn and skip. */
async function loadIconifyCollection(collectionName: string): Promise<IconifyJSON | undefined> {
  try {
    // Dynamic import during build.
    const module_ = await import(
      `@iconify-json/${collectionName}/icons.json`,
      { with: { type: 'json' } }
    );
    return module_.default as IconifyJSON;
  } catch (error) {
    logger.warn(`failed to load iconify collection '${collectionName}':`, error);
    return undefined;
  }
}

// CSS indentation is the optional `indent` parameter (default
// two spaces), threaded through `buildCSS` to the block-wrapping
// emitters: `buildRootBlock`, `buildBaseRule`, `buildBrandRule`.
// Body helpers (`buildBrandIconVariable`, `buildIconVars`) emit
// unindented declarations and let the wrapper apply the prefix.
// Per-function TSDoc stays silent on `indent` to avoid repetition.
//
// `-webkit-mask*` lines in `buildBaseRule` and `buildBrandRule`
// mirror the unprefixed properties for Safari < 15.4 (March 2022).
// Drop them once browserslist excludes Safari 15.3 and older.

/** Build a single `--icon-<name>` declaration, or warn and skip. */
function buildBrandIconVariable(
  collectionName: string,
  iconName: string,
  collection: IconifyJSON,
): string | undefined {
  const icon = collection.icons[iconName];
  if (!icon) {
    logger.warn(`icon '${iconName}' not found in '${collectionName}'`);
    return undefined;
  }
  const width = icon.width ?? collection.width ?? 24;
  const height = icon.height ?? collection.height;
  const uri = svgDataURI(wrapBrandSVG(icon.body, width, height));
  return `--icon-${iconName}: url('${uri}');`;
}

/**
 * Build all `--icon-*` declarations and report which brands had
 * their icon found. The caller skips the cascade rule for any
 * brand absent from `brands` so it never references an undefined
 * `--icon-*` var (which CSS resolves to `unset`, leaving the
 * `::after` as a solid `currentColor` block). When `collection`
 * is `undefined` (load failed), only the external-link var is
 * emitted and `brands` is empty.
 */
function buildIconVars(
  collectionName: string,
  collection: IconifyJSON | undefined,
  brandIcons: readonly BrandIcon[],
  externalLinkSvg: string,
): { brands: readonly BrandIcon[]; vars: readonly string[] } {
  const externalLink =
    `--icon-external-link: url('${svgDataURI(externalLinkSvg)}');`;
  if (!collection) return { vars: [externalLink], brands: [] };
  const vars: string[] = [externalLink];
  const brands: BrandIcon[] = [];
  for (const brand of brandIcons) {
    const declaration = buildBrandIconVariable(collectionName, brand.name, collection);
    if (declaration === undefined) continue;
    vars.push(declaration);
    brands.push(brand);
  }
  return { vars, brands };
}

/**
 * Wrap a list of CSS custom-property declarations in a `:root { … }`
 * block.
 */
function buildRootBlock(vars: readonly string[], indent: string = DEFAULT_INDENT): string {
  const indented = vars.map((v) => `${indent}${v}`);
  return [':root {', ...indented, '}'].join('\n');
}

/**
 * Normalise a brand icon's `host` field into a list of validated
 * bare hostnames. Each entry is tested against `HOST_PATTERN`;
 * mismatches are logged via consola and dropped. Returns
 * `undefined` when the source list is empty or no valid hosts
 * survive — caller skips the brand on `undefined`.
 */
function asBrandHosts(icon: BrandIcon): readonly string[] | undefined {
  const raw: readonly string[] = typeof icon.host === 'string' ? [icon.host] : icon.host;
  if (raw.length === 0) {
    logger.error(`brand '${icon.name}' has no hosts`);
    return undefined;
  }
  const hosts = raw.filter((host) => {
    const valid = HOST_PATTERN.test(host);
    if (!valid) {
      logger.error(`brand '${icon.name}' has invalid host '${host}' — bare hostname expected`);
    }
    return valid;
  });
  return hosts.length > 0 ? hosts : undefined;
}

/**
 * Build a CSS attribute-selector fragment matching anchors that
 * point at any of the given hosts. Each host becomes an anchored
 * `[href^="https://host/" i]` selector; multi-host lists are
 * wrapped in `:is(…)` so the rule still expresses one logical
 * match. Anchored prefixes rule out incidental substring hits in
 * URL paths or query strings. Returns `''` for `undefined` or
 * empty input — callers treat the empty matcher as "skip".
 * Typically fed the output of `asBrandHosts`, which
 * pre-validates hosts.
 */
function buildHostMatcher(hosts: readonly string[] | undefined): string {
  const selectors = (hosts ?? []).map((host) => `[href^="https://${host}/" i]`);
  switch (selectors.length) {
    case 0: return '';
    case 1: return selectors[0]!;
    default: return `:is(${selectors.join(',')})`;
  }
}

/**
 * Build the cascade override rule for one brand icon, or `undefined`
 * when no valid hosts survived `asBrandHosts` (which logs the
 * error itself). Caller filters `undefined` out of the rule list.
 */
function buildBrandRule(icon: BrandIcon, indent: string = DEFAULT_INDENT): string | undefined {
  const matcher = buildHostMatcher(asBrandHosts(icon));
  if (!matcher) return undefined;
  return `\
.prose a${matcher}:not(:has(img))::after {
${indent}-webkit-mask-image: var(--icon-${icon.name});
${indent}mask-image: var(--icon-${icon.name});
}`;
}

/**
 * Build the base `.prose a[href^="http" i]` rule that decorates
 * every external link with the generic external-link glyph.
 */
function buildBaseRule(indent: string = DEFAULT_INDENT): string {
  return `\
.prose a[href^="http" i]:not(:has(img))::after {
${indent}content: "";
${indent}display: inline-block;
${indent}width: 0.85em;
${indent}height: 0.85em;
${indent}margin-left: 0.2em;
${indent}vertical-align: -0.1em;
${indent}background-color: currentColor;
${indent}-webkit-mask: var(--icon-external-link) center / contain no-repeat;
${indent}mask: var(--icon-external-link) center / contain no-repeat;
}`;
}

/** Compose the decoration CSS: base rule, then one cascade per brand. */
function buildDecorationCSS(
  brandIcons: readonly BrandIcon[],
  indent: string = DEFAULT_INDENT,
): string {
  const baseRuleComment = `\
/* External-link icon decoration. Scoped to .prose so the chrome
   (ProjectMeta badges, GitHub repo link) is untouched. The
   \`[href^="http" i]\` clause matches both plain markdown links
   (which @nuxt/content renders without \`target="_blank"\`) and
   component anchors that set it explicitly; the \`i\` flag tolerates
   uppercase schemes. The \`:not(:has(img))\` clause excludes any
   \`:badge-version-*\` MDC component used inside markdown — those
   anchors wrap an <img> shield and keep their own visual identity. */`;
  const brandRules = brandIcons
    .map((icon) => buildBrandRule(icon, indent))
    .filter((rule): rule is string => rule !== undefined);
  const blocks = [
    `${baseRuleComment}\n${buildBaseRule(indent)}`,
    ...brandRules,
  ];
  return blocks.join('\n\n') + '\n';
}

/**
 * Compose the full CSS file content from a (possibly missing) icon
 * collection. The brand cascade rules are scoped to brands whose
 * icons were successfully resolved, so a missing collection or a
 * missing icon degrades to "external-link glyph only" rather than
 * an undefined-var-induced visual glitch.
 */
function buildCSS(
  collectionName: string,
  collection: IconifyJSON | undefined,
  brandIcons: readonly BrandIcon[],
  externalLinkSvg: string,
  indent: string = DEFAULT_INDENT,
): string {
  const { vars, brands } = buildIconVars(collectionName, collection, brandIcons, externalLinkSvg);
  return [
    HEADER_COMMENT,
    buildRootBlock(vars, indent),
    '',
    buildDecorationCSS(brands, indent),
  ].join('\n');
}

export default defineNuxtModule<ModuleOptions>({
  meta: { name: TEMPLATE_NAME, configKey: 'externalLinkIcons' },
  defaults: DEFAULT_OPTIONS,
  setup(options, nuxt) {
    const { collection: collectionName, brands, externalLinkSvg, indent } = options;
    const template = addTemplate({
      filename: TEMPLATE_FILENAME,
      write: true,
      async getContents() {
        const collection = await loadIconifyCollection(collectionName);
        return buildCSS(collectionName, collection, brands, externalLinkSvg, indent);
      },
    });

    nuxt.options.css.push(template.dst);
  },
});
